### ISSUE TITLE
wb fill incredibly slow 

### ISSUE THREAD

**Issue by Saelman** [Brettflan/WorldBorder#183]
Hi, im trying to generate a 20kX20k area using fill, and currently i cant get it to load anything over 100 chunks each time.
theres still plenty of ram left (6gigs),  so im not throttling there. 

[18:34:10 INFO]: [WorldBorder] [Fill] 18 more chunks processed (142596 total, ~8.7%) (free mem: 6257 MB)
[18:34:15 INFO]: [WorldBorder] [Fill] 16 more chunks processed (142612 total, ~8.7%) (free mem: 6417 MB)
[18:34:16 WARN]: Can't keep up! Is the server overloaded? Running 19957ms or 399 ticks behind
[18:34:20 INFO]: [WorldBorder] [Fill] 16 more chunks processed (142628 total, ~8.7%) (free mem: 6123 MB)
[18:34:25 INFO]: [WorldBorder] [Fill] 12 more chunks processed (142640 total, ~8.7%) (free mem: 6473 MB)
[18:34:32 INFO]: [WorldBorder] [Fill] 65 more chunks processed (142705 total, ~8.7%) (free mem: 6359 MB)

this is pretty much the constant rate of loading.
if you need any other info, i can totally submit that, just not sure what all you need for this.

**Comment by TheCompieter** [comment]
@Saelman this is because the worldborder requests chunk unloads too prevent the server from running quickly out of memory this causes the slowdown if you want faster world generation with the cost of more memory usage you should use an fork of worldborder where this is fixed i can give you an build or you can build it yourself with intellij if you want. the issues linked is here #173

**Comment by edwerd** [comment]
@TheCompieter @Puremin0rez Where could I find a compiled version of this fix?

**Comment by compieter-gh** [comment]
@edwerd 
https://github.com/TheCompieter/WorldBorder/releases/tag/v1.10.1

**Comment by edwerd** [comment]
@TheCompieter Sadly, this issue didn't fix my memory leak.

<img width="1033" alt="wb-fill" src="https://user-images.githubusercontent.com/1358022/81231359-0a26da80-8fc1-11ea-9646-2fc8276e66e4.png">

**Comment by TheCompieter** [comment]
@edwerd how much memory does you minecraft server have and what version (for example spigot/paper 1.15.2) are you running?

**Comment by compieter-gh** [comment]
@edwerd try latest release that includes the fix for unloading chunks when memory is low.
https://github.com/TheCompieter/WorldBorder/releases/tag/v1.10.1
